### ISSUE TITLE
Add ability to lookup services from different hosts

### ISSUE THREAD

**Issue by at88mph** [opencadc/reg#10]
The current functionality seems to only allows looking up of services from a single host; meaning all services need to be running together on one host.

In the interest of distributed services and applications, it would be necessary to allow looking up services from different hosts.

In a use case where an organization wants to deploy AC on a.web.host and VOSPACE on b.web.host, maybe a solution is to pass in a `ca.nrc.cadc.reg.client.RegistryClient.<SERVICE>.host=<HOST>` per deployment, or to further customize the `capabilities.xml`.

**Comment by pdowler** [comment]
The current code already allows for services to run on different hosts in production via the embedded config file in cadc-registry;  the system properties are only included for development support.

In order to support a distributed dev environment, we would have to move to getting that bootstrap info from the environment (e.g. a registry service)... intentionally vague to not pre-suppose the solution. Extending the current system-prop override solution isn't really feasible.
